[package]
name = "aoc-2020"
version = "0.1.0"
authors = ["Aaron Sky <aaronsky@skyaaron.com>"]
edition = "2018"
publish = false

[dependencies]
itertools = "0.9"
lazy_static = "1"
regex = "1"
util = { path = "../util" }
