name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch: ~

jobs:
  build:
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: |- 
          swift test \
            --skip "Advent2015Tests" \
            --skip "Advent2016Tests" \
            --skip "Advent2017Tests" \
            --skip "Advent2018Tests" \
            --skip "Advent2019Tests" \
            --skip "Advent2020Tests" \
            --skip "Advent2021Tests"
